[package]
name = "rosalind"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dna"
path = "src/bin/dna.rs"
[[bin]]
name = "rna"
path = "src/bin/rna.rs"
[[bin]]
name = "revc"
path = "src/bin/revc.rs"

[dependencies]
